apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: mongo
    name: mongo
  spec:
    ports:
      - port: 27017
        targetPort: 27017
    selector:
      name: demo
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      name: demo
    name: controllers
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: demo
    template:
      metadata:
        labels:
          name: demo
        name: demo
      spec:
        containers:
        - image: mongo
          name: mongo
          ports:
          - name: mongo
            containerPort: 27017
            hostPort: 27017
        - image: node:0.10.40
          command: ['/bin/sh', '-c']
          args: ['tail -f /dev/null']
          name: nodejs
          ports:
          - containerPort: 3000
            name: http-server
- apiVersion: v1
  kind: Service
  metadata:
    name: web
    labels:
      name: web
  spec:
    ports:
      - port: 3000
        targetPort: 3000
        protocol: TCP
    selector:
      name: demo
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: nodejs-ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  spec:
    rules:
    - host: 192.168.99.100.nip.io
      http:
        paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 3000
